FORMAT: 1A
HOST: http://localhost/content/v1

# babe-content-ms

Content Microservice main goal is to provide fast and reliable content access.
 
It should encapsulates all underlying storage & cache and provide convenient interface for content client.

# Group Article

## Article Alteration [/art/bulk]

### <a name="bulk-remove"></a> Bulk Article Removal [DELETE]

Remove article by indices supplied from Babe backend system.

The order of removal described below:

1. UPDATE `status` in table `sasha_article` to inactive, `status = -1`
2. DELETE `solr` document based on `article_id_l`
3. DELETE redis key `x-art:{artId}` (Article Detail)
5. DELETE redis key `x-art-likes:{artId}` (Likes for article)
6. DELETE redis key `x-art-dislikes:{artId}` (Dislikes for article) 
7. DELETE member in redis key `x-list:{catName}` (List Category)
8. DELETE redis key `x-pub-rel-art:{artId}` (Article Publisher Related)
9. DELETE member in redis key `x-list-popular:{catId}` (List Popular)
10. DELETE redis key `x-comment:{commentId}` (Comment Detail)
11. DELETE redis key `x-art-comment:{artId}` (List Comment on Article)
12. DELETE redis key `x-art-comment-r:{artId}` (List Comment Report)
13. DELETE redis key `x-art-comment-m:{artId}` (List Comment Mood)

Then return all article indices that are successfully pass all the above process.

+ Request (application/json)
    + Attributes
        + ids: 60001, 60003, 89001, 90400, 99181 (array[number], required) - Article Indides to be deleted.
        
+ Response 200 (application/json)
    + Attributes (array, number) - Article Indices which are successfully removed.
        + 60001
        + 89001
        + 99181

+ Response 400 (application/json)
    Return when parameters requirement not met correctly
    
    + Attributes (DefaultError400)
    
+ Response 413 (application/json)
    Return when request data is too big (limit configurable)
    
    + Attributes (DefaultError413)
        
+ Response 503 (application/json)
    Return when server has internal error and can't continue fulfilling the request

    + Attributes (DefaultError503)

### Article Removal by Publisher [DELETE /art/bulk/pub/{pubId}]

Remove all article from specified publisher ID.

Logic of the removal is the same as [bulk article removal](#bulk-remove)

Return number of article that is successfully removed.

+ Parameters
    + pubId: 87 (string, required) - Publisher ID
    
+ Response 200 (application/json)
    + Attributes
        + count: 11000 (string) - Number of actual deleted article.

+ Response 404 (application/json)
    Return when publisher id is not found
    
    + Attributes (DefaultError404)
    
+ Response 413 (application/json)
    Return when request data is too big (limit configurable)
    
    + Attributes (DefaultError413)
        
+ Response 503 (application/json)
    Return when server has internal error and can't continue fulfilling the request

    + Attributes (DefaultError503)

### Article Removal by Source [DELETE /art/bulk/src/{srcId}]

Remove all article from specified source ID.

Logic of the removal is the same as [bulk article removal](#bulk-remove)

Return number of article that is successfully removed.

+ Parameters
    + srcId: 37 (string, required) - Source ID
    
+ Response 200 (application/json)
    + Attributes
        + count: 2400 (string) - Number of actual deleted article.

+ Response 404 (application/json)
    Return when source id is not found
    
    + Attributes (DefaultError404)
    
+ Response 413 (application/json)
    Return when request data is too big (limit configurable)
    
    + Attributes (DefaultError413)
        
+ Response 503 (application/json)
    Return when server has internal error and can't continue fulfilling the request

    + Attributes (DefaultError503)





# Data Structures

## Error (object)
+ errCode (number) - Error Code
+ errMsg (string) - Error Message

## DefaultError400 (Error)
+ errCode: `-1`
+ errMsg: Invalid Request

## DefaultError401 (Error)
+ errCode: `-2`
+ errMsg: Authorization needed to access resource

## DefaultError404 (Error)
+ errCode: `-5`
+ errMsg: Resource not found

## DefaultError413 (Error)
+ errCode: `-14`
+ errMsg: Request Entity Too Large

## DefaultError503 (Error)
+ errCode: `-10`
+ errMsg: Backend service is down